name: dnds_pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pandas
  - biopython
  - numpy
  - pyyaml
  - mafft
  - pal2nal
  - paml
  - parallel
  - r-base>=4.0
  - r-tidyverse
  - r-data.table
  - r-readr
  - r-ggpubr
  - r-patchwork
  - r-rstatix
  - r-broom
  - r-scales
  - r-cairo
