#!/usr/bin/env python3

"""
03b_alignment_quality_stats.py

Calculate quality statistics for codon alignments generated by PAL2NAL.
"""

import argparse
import os
import re
import yaml
import pandas as pd


def load_config(config_file):
    with open(config_file, "r") as handle:
        return yaml.safe_load(handle)


def parse_phylip(filepath):
    """
    Parse sequential PHYLIP format generated by PAL2NAL.
    Returns a list of two tuples: [(name1, seq1), (name2, seq2)].
    """

    with open(filepath, "r") as handle:
        lines = [line.rstrip("\n\r") for line in handle]

    if len(lines) < 3:
        return None

    header = lines[0].strip().split()
    if len(header) < 2:
        return None

    nseq = int(header[0])
    expected_length = int(header[1])

    if nseq != 2:
        return None

    sequences = {}
    current_name = None

    for line in lines[1:]:
        line = line.strip()
        if not line:
            continue

        if not re.match(r"^[ATCGN\-]+$", line, re.IGNORECASE):
            current_name = line
            sequences[current_name] = ""
        else:
            if current_name is not None:
                sequences[current_name] += line

    if len(sequences) != 2:
        return None

    seq_list = list(sequences.items())

    for _, seq in seq_list:
        if len(seq) != expected_length:
            return None

    return seq_list


def calculate_gc(seq):
    clean_seq = seq.replace("-", "").upper()
    if len(clean_seq) == 0:
        return 0
    return 100 * (clean_seq.count("G") + clean_seq.count("C")) / len(clean_seq)


def analyze_alignment_file(filepath):
    og_id = os.path.basename(filepath).replace(".phy", "")

    parsed = parse_phylip(filepath)

    if parsed is None:
        return None, f"{og_id}: parse_failed"

    if len(parsed) != 2:
        return None, f"{og_id}: not_two_sequences"

    seq1_name, seq1 = parsed[0]
    seq2_name, seq2 = parsed[1]

    seq1 = seq1.upper()
    seq2 = seq2.upper()

    if len(seq1) != len(seq2):
        return None, f"{og_id}: unequal_sequence_lengths"

    alignment_length = len(seq1)

    if alignment_length % 3 != 0:
        return None, f"{og_id}: length_not_multiple_of_three"

    effective_codons = alignment_length // 3

    gaps1 = seq1.count("-")
    gaps2 = seq2.count("-")
    gap_percentage = 100 * (gaps1 + gaps2) / (alignment_length * 2)

    stop_codons = {"TAA", "TAG", "TGA"}
    internal_stops = 0

    for i in range(0, alignment_length - 3, 3):
        codon1 = seq1[i : i + 3]
        codon2 = seq2[i : i + 3]

        if "-" not in codon1 and codon1 in stop_codons:
            internal_stops += 1
        if "-" not in codon2 and codon2 in stop_codons:
            internal_stops += 1

    gc1 = calculate_gc(seq1)
    gc2 = calculate_gc(seq2)

    matches = sum(1 for a, b in zip(seq1, seq2) if a == b and a != "-")
    non_gap_positions = sum(1 for a, b in zip(seq1, seq2) if a != "-" or b != "-")
    identity = 100 * matches / non_gap_positions if non_gap_positions > 0 else 0

    result = {
        "Orthogroup": og_id,
        "Species1": seq1_name,
        "Species2": seq2_name,
        "Alignment_Length_bp": alignment_length,
        "Effective_Codons": effective_codons,
        "Effective_Length_1": len(seq1.replace("-", "")),
        "Effective_Length_2": len(seq2.replace("-", "")),
        "Gap_Percentage": round(gap_percentage, 2),
        "Internal_Stops": internal_stops,
        "GC_Content_1": round(gc1, 2),
        "GC_Content_2": round(gc2, 2),
        "Avg_GC_Content": round((gc1 + gc2) / 2, 2),
        "Sequence_Identity": round(identity, 2),
    }

    return result, None


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="config.yaml", help="Path to config.yaml")
    args = parser.parse_args()

    config = load_config(args.config)

    codon_dir = config["output"]["codon_alignment_dir"]
    work_dir = config["output"]["work_dir"]
    log_dir = config["output"]["logs_dir"]

    os.makedirs(work_dir, exist_ok=True)
    os.makedirs(log_dir, exist_ok=True)

    output_file = os.path.join(work_dir, "alignment_length_stats.csv")
    error_file = os.path.join(log_dir, "alignment_errors.log")
    high_quality_file = os.path.join(work_dir, "high_quality_genes.txt")
    problem_file = os.path.join(work_dir, "problem_genes.csv")

    print("=" * 80)
    print("Step 3b: Codon alignment quality statistics")
    print("=" * 80)

    if not os.path.exists(codon_dir):
        raise FileNotFoundError(f"Codon alignment directory not found: {codon_dir}")

    phylip_files = sorted(
        [
            os.path.join(codon_dir, f)
            for f in os.listdir(codon_dir)
            if f.endswith(".phy")
        ]
    )

    print(f"Found {len(phylip_files)} codon alignment files.")

    results = []
    errors = []

    for i, filepath in enumerate(phylip_files, start=1):
        result, error = analyze_alignment_file(filepath)

        if result is not None:
            results.append(result)
        else:
            errors.append(error)

        if i % 1000 == 0:
            print(f"Processed {i}/{len(phylip_files)} files.")

    if errors:
        with open(error_file, "w") as handle:
            handle.write("\n".join(errors))
        print(f"Alignment parsing errors saved: {error_file}")

    if not results:
        raise RuntimeError("No valid codon alignments were processed.")

    df = pd.DataFrame(results)
    df.to_csv(output_file, index=False)

    print(f"\nAlignment statistics saved: {output_file}")
    print(f"Successfully analyzed: {len(df)} alignments")
    print(f"Failed alignments: {len(errors)}")

    print("\nSummary of effective codon lengths:")
    print(df["Effective_Codons"].describe())

    print("\nQuality summary:")
    print(f"Mean gap percentage: {df['Gap_Percentage'].mean():.2f}%")
    print(f"Mean sequence identity: {df['Sequence_Identity'].mean():.2f}%")
    print(f"Mean GC content: {df['Avg_GC_Content'].mean():.2f}%")
    print(f"Alignments with internal stops: {(df['Internal_Stops'] > 0).sum()}")

    high_quality = df[
        (df["Gap_Percentage"] < 20)
        & (df["Internal_Stops"] == 0)
        & (df["Effective_Codons"] >= 50)
        & (df["Sequence_Identity"] >= 30)
    ]

    with open(high_quality_file, "w") as handle:
        for og in high_quality["Orthogroup"]:
            handle.write(f"{og}\n")

    problem_genes = df[
        (df["Gap_Percentage"] > 50)
        | (df["Internal_Stops"] > 0)
        | (df["Sequence_Identity"] < 30)
    ]

    problem_genes.to_csv(problem_file, index=False)

    print(f"High-quality gene list saved: {high_quality_file}")
    print(f"Problem gene table saved: {problem_file}")


if __name__ == "__main__":
    main()
