name: fungal_annotation
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pandas
  - numpy
  - openpyxl
  - diamond
  - hmmer
  - eggnog-mapper
  - kofamscan
  - seqkit
